[env:TST-Tester]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
; M5StickC Plus2 has 8MB flash (override m5stick-c default of 4MB)
board_build.flash_size = 8MB
board_upload.flash_size = 8MB

lib_deps =
    m5stack/M5Unified
    robtillaart/RunningAverage@^0.4.8
    robtillaart/RunningMedian@^0.3.7
    h2zero/NimBLE-Arduino@^1.4.1

lib_ignore =
    DFRobot_GP8XXX

[env:Calibration]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<main.cpp> +<../calibration/calibration.cpp>

lib_deps =
    m5stack/M5Unified
    robtillaart/RunningAverage@^0.4.8

lib_ignore =
    DFRobot_GP8XXX
