[env:TST-Tester-Core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

build_flags =
    -I../TST-Tester_CP2/include

lib_deps =
    m5stack/M5Unified
    robtillaart/RunningAverage@^0.4.8
    robtillaart/RunningMedian@^0.3.7
    h2zero/NimBLE-Arduino@^1.4.1

lib_ignore =
    DFRobot_GP8XXX

[env:Calibration]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<main.cpp> +<../calibration/calibration.cpp>

build_flags =
    -I../TST-Tester_CP2/include

lib_deps =
    m5stack/M5Unified
    robtillaart/RunningAverage@^0.4.8

lib_ignore =
    DFRobot_GP8XXX
