[env:TST-Tester-StickCPlus]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
; M5StickC Plus has 4MB flash (default for m5stick-c board)

build_flags =
    -I../TST-Tester_CP2/include

lib_deps =
    m5stack/M5Unified
    robtillaart/RunningAverage@^0.4.8
    robtillaart/RunningMedian@^0.3.7
    h2zero/NimBLE-Arduino@^1.4.1

lib_ignore =
    DFRobot_GP8XXX
